bases:
  - environments.yaml

repositories:
  - name: knative-operator
    url: https://knative.github.io/operator

releases:
  - name: knative-operator
    chart: knative-operator/knative-operator
    version: v1.18.1
    namespace: knative-operator
    createNamespace: true
  
  - name: knative
    chart: ./charts/knative
    namespace: knative
    createNamespace: true
    needs:
      - knative-operator/knative-operator